eclipse-uprotocol/up-java

- src/main/java/org/eclipse/uprotocol/uri/datamodel/UUri.java
- src/main/java/org/eclipse/uprotocol/uri/factory/UriFactory.java
- src/test/java/org/eclipse/uprotocol/uri/factory/UriFactoryTest.java
Adding methods to support older/proprietary scheme or blank scheme in the URI. This does not change the datamodel of URI for uProtocol
> Scheme URI Building

- .github/workflows/build_and_test.yml
Adds a build and test github action for the java sdk repo. Essentially takes the starter workflow for building with Maven (found [here](https://github.com/actions/starter-workflows/blob/main/ci/maven.yml) and comments out the optional dependency graph update as that requires some other configuration (found [here](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/configuring-the-dependency-graph)).
Validated in forked repository that the build and test workflow executes as expected when a pull request is made into main:
Here are some screenshots of the workflow running:
Build executing:
Build complete and test starting:
test completing:
Success at the end:
> Add build and test github action for java sdk repo

- src/main/java/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactory.java
- src/main/java/org/eclipse/uprotocol/cloudevent/serialize/CloudEventToJsonSerializer.java
- src/test/java/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactoryTest.java
The following change removes datacontenttype and dataschema from cloudevent attributes as they are optional and not used/needed. To support this change, Jackson JSON parser needs to be explicitly told that the data is always base64 encoded.
#13
> Removed unused attributes

- src/main/java/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactory.java
Production version of uProtocol (1.3.7) used UUIDv6 and changing to v8 would result in a non-backwards compatible change as CloudEvents assume v6 because of the Validators that are used in devices. In order to change versions of UUIDs, we'll need to update the message type version (ex. pub.v1 to pub.v2), something to be considered at a later date.
#15
> Revert default UUID to v6

- src/main/java/org/eclipse/uprotocol/cloudevent/datamodel/UCloudEventAttributes.java
- src/test/java/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactoryTest.java
Remove references to old internal specifications name
> Remove SDV-202 references

- src/main/java/org/eclipse/uprotocol/cloudevent/datamodel/UCloudEventAttributes.java
- src/main/java/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactory.java
- src/test/java/org/eclipse/uprotocol/cloudevent/datamodel/UCloudEventAttributesTest.java
- src/test/java/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactoryTest.java
- src/test/java/org/eclipse/uprotocol/cloudevent/factory/UCloudEventTest.java
- src/test/java/org/eclipse/uprotocol/cloudevent/serialize/CloudEventToJsonSerializerTest.java
- src/test/java/org/eclipse/uprotocol/cloudevent/serialize/CloudEventToProtobufSerializerTest.java
- src/test/java/org/eclipse/uprotocol/cloudevent/validate/CloudEventValidatorTest.java
In this commit, we've taken out the Priority enum from the UCloudAttributes class and replaced it with the UPriority enum as defined in the uattributes.proto file. This change guarantees a uniform use of priority across the entire codebase.
> Remove 'Priority' enum from UCloudAttributes class

- src/main/java/org/eclipse/uprotocol/cloudevent/factory/UCloudEvent.java
- src/test/java/org/eclipse/uprotocol/cloudevent/factory/UCloudEventTest.java
This commit addresses issue #51 by adding two new methods "fromMessage" and "toMessage" in UCloudEvent class to handle the conversion between CloudEvent and UMessage.
> Add methods for CloudEvent ↔ UMessage conversion

- pom.xml
This commit addresses issue #54 by eliminating the uprotocol-core-api dependency. Protos are now pulled directly from GitHub and compiled within the project
> Remove uprotocol-core-api dependency

- src/main/java/org/eclipse/uprotocol/transport/validate/UAttributesValidator.java
- src/test/java/org/eclipse/uprotocol/transport/validator/UAttributesValidatorTest.java
This commit addresses Issue #64 , where the UAttributesValidator was found to incorrectly handle the sink attribute for RPC request and response messages.
> Fix: UAttributesValidator now correctly handles the sink attribute.

- src/main/java/org/eclipse/uprotocol/rpc/RpcClient.java
- src/main/java/org/eclipse/uprotocol/rpc/RpcMapper.java
- src/test/java/org/eclipse/uprotocol/rpc/RpcTest.java
> Change InvokeMethod() to return UMessage

- src/main/java/org/eclipse/uprotocol/cloudevent/factory/UCloudEvent.java
In lieu of a switch statement and static defining the mime type, pull the mime type from the proto generated code
#71
> Fetch Mime Type From EnumDescriptor

- src/main/java/org/eclipse/uprotocol/cloudevent/README.adoc
Update link to cloudevents doc to resolve issue #98
Readme file "Overview" section have a wrong link to [cloudevents.adoc](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/cloudevents.adoc)
> Update link to Cloudevents doc

- src/test/java/org/eclipse/uprotocol/uri/factory/UEntityFactoryTest.java
Incorporate the retagging of uprotocol-core-api-1.5.7 to fix the utwin packaging issue, it was using v1 when it should have been in v2.
> Fix the uTwin package number

- pom.xml
the current up-java version of 1.5.x was out of sync with the up-core-api/up-spec version numbers so there was confusion on if the two are related meaning is 1.5.7 of up-java the same as 1.5.7 of up-core-api and they are not. In order to avoid confusion, we are renaming the up-java to 0.1.9 and we will add the up-core-api-1.5.7 tag as well so we know what version this support of up-core-api.
> Change up-java versions

- src/main/java/org/eclipse/uprotocol/transport/validate/UAttributesValidator.java
- src/test/java/org/eclipse/uprotocol/transport/validator/UAttributesValidatorTest.java
> Add validation for id property in uattributes

- src/main/java/org/eclipse/uprotocol/uri/serializer/ShortUriSerializer.java
- src/test/java/org/eclipse/uprotocol/uri/serializer/ShortUriSerializerTest.java
The ShortUriSerializer uses InetAddress.toString() to produce the
textual representation of the IP address contained in a UAuthority.
In doing so, it assumes that the IP address' hostname is empty and
thus toString() yields something like /192.168.1.10,
i.e. starts with a slash.
While this assumption is correct for the IP addresses used in
UAuthority (which contain no hostname) in this case, the usage of
the toString() method has been replaced with getHostAddress()
which yields only the textual representation of the IP address' bytes
and therefore seems better suited for the purpose of serializing
the address to short format.
Fixes #103
> Improve serialization to short format

- src/main/java/org/eclipse/uprotocol/uri/serializer/LongUriSerializer.java
- src/test/java/org/eclipse/uprotocol/uri/serializer/LongUriSerializerTest.java
It is not sufficient to check UUri::hasAuthority() or UResource::hasInstance() or UResource::hasMessage() as they might be set to blank strings that are invalid. The following change also checks if the string is blank or not.
#107
> Check UAuthority and UResource names are not blank

- .github/workflows/coverage-comment-pr.yml
- .github/workflows/coverage.yml
- pom.xml
- Implement workflow to measure test code coverage.
- Generate coverage reports after tests are executed.
- Add support for posting coverage comments on PRs from forks. 
I have tested these workflows in my own fork, keep in mind that this only works once the additional workflow is available in the main branch, thus after this PR has been merged.
Here is the screenshot from my own fork
> Add workflow for test coverage report and PR coverage comments

- .github/workflows/lint.yml
- checkstyle.xml
- pom.xml
- src/main/java/org/eclipse/uprotocol/cloudevent/datamodel/UCloudEventAttributes.java
- src/main/java/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactory.java
- src/main/java/org/eclipse/uprotocol/cloudevent/factory/UCloudEvent.java
- src/main/java/org/eclipse/uprotocol/cloudevent/serialize/Base64ProtobufSerializer.java
- src/main/java/org/eclipse/uprotocol/cloudevent/serialize/CloudEventSerializers.java
- src/main/java/org/eclipse/uprotocol/cloudevent/serialize/CloudEventToJsonSerializer.java
- src/main/java/org/eclipse/uprotocol/cloudevent/serialize/CloudEventToProtobufSerializer.java
- src/main/java/org/eclipse/uprotocol/cloudevent/validate/CloudEventValidator.java
- src/main/java/org/eclipse/uprotocol/transport/UListener.java
- src/main/java/org/eclipse/uprotocol/transport/UTransport.java
- src/main/java/org/eclipse/uprotocol/transport/builder/UMessageBuilder.java
- src/main/java/org/eclipse/uprotocol/transport/validate/UAttributesValidator.java
- src/main/java/org/eclipse/uprotocol/uri/factory/UriFactory.java
- src/main/java/org/eclipse/uprotocol/uri/serializer/UriSerializer.java
- src/main/java/org/eclipse/uprotocol/uri/validator/UriValidator.java
- src/main/java/org/eclipse/uprotocol/uuid/factory/UuidFactory.java
- src/main/java/org/eclipse/uprotocol/uuid/factory/UuidUtils.java
- src/main/java/org/eclipse/uprotocol/uuid/serializer/UuidSerializer.java
- src/main/java/org/eclipse/uprotocol/uuid/validate/UuidValidator.java
- src/main/java/org/eclipse/uprotocol/validation/ValidationResult.java
Addressed issues detected by Checkstyle and PMD, including:
- Correcting naming conventions.
- Removing unused imports.
- Fixing formatting errors.
- Ensuring proper indentation.
- Explicitly declaring visibility modifiers.
- Hard wrapping lines at 120 characters
**Checkstyle** : For enforcing coding standards and style guidelines.
**PMD**  : For detecting unused variables, and other potential issues. It finds common programming flaws like unused variables, empty catch blocks, unnecessary object creation, and so forth.
> Add linting workflow and address identified issues 

- src/main/java/org/eclipse/uprotocol/cloudevent/factory/CloudEventFactory.java
- src/main/java/org/eclipse/uprotocol/cloudevent/factory/UCloudEvent.java
- src/main/java/org/eclipse/uprotocol/cloudevent/validate/CloudEventValidator.java
- src/main/java/org/eclipse/uprotocol/uuid/factory/UuidFactory.java
- src/main/java/org/eclipse/uprotocol/uuid/factory/UuidUtils.java
- src/main/java/org/eclipse/uprotocol/uuid/validate/UuidValidator.java
- src/test/java/org/eclipse/uprotocol/cloudevent/validate/CloudEventValidatorTest.java
- src/test/java/org/eclipse/uprotocol/uuid/factory/UUIDFactoryTest.java
- src/test/java/org/eclipse/uprotocol/uuid/validator/UuidValidatorTest.java
The following change removes the v8 custom UUID to the v7 standard definition per up-spec change https://github.com/eclipse-uprotocol/up-spec/issues/170
#125
> Update to UUIDv7

- src/main/java/org/eclipse/uprotocol/transport/validate/UAttributesValidator.java
- src/test/java/org/eclipse/uprotocol/transport/validator/UAttributeValidatorTest.java
Per the specification, UMessages (publish, notification, request, response) MUST have a priority of CS1 or greater but before it was only checking that priority was greater than CS0.
#131
> Fix Priority Validation for UAttributes

- src/main/java/org/eclipse/uprotocol/communication/Notifier.java
- src/main/java/org/eclipse/uprotocol/communication/Publisher.java
- src/main/java/org/eclipse/uprotocol/communication/SimpleNotifier.java
- src/main/java/org/eclipse/uprotocol/communication/SimplePublisher.java
- src/main/java/org/eclipse/uprotocol/communication/UClient.java
- src/test/java/org/eclipse/uprotocol/communication/NotifierExampleTest.java
- src/test/java/org/eclipse/uprotocol/communication/PublisherExampleTest.java
- src/test/java/org/eclipse/uprotocol/communication/SimpleNotifierTest.java
- src/test/java/org/eclipse/uprotocol/communication/SimplePublisherTest.java
- src/test/java/org/eclipse/uprotocol/communication/UClientTest.java
CallOptions contains additional attributes that an application might want to set before the message is sent so we pass them to the publish() and notify() APIs. Additionally, I added default APIs for when passed parameters are null (we don't want to pass them).
#130
> Add CallOptions to Notifier & Publisher

- pom.xml
In order to ensure the release will pull a stable version, we are setting the version of up-spec to be the latest release version.
> Peg the version of up-spec to v1.6.0-alpha.2

- src/main/java/org/eclipse/uprotocol/uri/factory/UriFactory.java
- src/main/java/org/eclipse/uprotocol/uri/serializer/UriSerializer.java
- src/main/java/org/eclipse/uprotocol/uri/validator/UriValidator.java
- src/test/java/org/eclipse/uprotocol/uri/validator/UriValidatorTest.java
- Implement pattern matching functions for authority, entity ID, instance, version, and resource as per [up-spec#pattern-matching](https://github.com/eclipse-uprotocol/up-spec/blob/main/basics/uri.adoc#5-pattern-matching)
- Add tests for identical URIs, wildcards, and various mismatch scenarios.
- #139
> Add uri pattern matching logic and test cases

- src/main/java/org/eclipse/uprotocol/communication/InMemorySubscriber.java
- src/main/java/org/eclipse/uprotocol/communication/UClient.java
- src/test/java/org/eclipse/uprotocol/communication/InMemorySubscriberTest.java
- src/test/java/org/eclipse/uprotocol/uri/validator/UriValidatorTest.java
The subscribe API is now idempotent and we fixed unsubscribe() so that there is no issue where we unsubscribe but an handler or listener stays registered.
#140
> Address issues in InMemorySubscriber

- src/main/java/org/eclipse/uprotocol/communication/UPayload.java
The newly added pack and unbpack messages were not public so people using up-java was not able to call them.
#149
> Make uPayload static methods public

- src/main/java/org/eclipse/uprotocol/uri/validator/UriFilter.java
- src/test/java/org/eclipse/uprotocol/uri/validator/UriFilterTest.java
The UriFilter class is used to match a source and sink URI to UAttributes that is passed. This can be used within a transport to match incoming messages
#147
> Adding UriFilter

- src/main/java/org/eclipse/uprotocol/transport/UTransport.java
- src/test/java/org/eclipse/uprotocol/transport/UTransportTest.java
Some transports require initialization that should not be done inside of the constructor so we add the open() API that can be implemented to do the async initialization of the underlining transport.
#146
> Add open() API to UTransport

- src/main/java/org/eclipse/uprotocol/communication/InMemoryRpcClient.java
- src/test/java/org/eclipse/uprotocol/communication/InMemoryRpcClientTest.java
- src/test/java/org/eclipse/uprotocol/communication/TestUTransport.java
Previously, the InMemoryRpcClient raised a UStatusException if the message had any communication status without checking its value. According to the up-spec, a communication status value of 0 or no value indicates no communication error. The exception should only be raised if the communication status value is non-zero. This commit updates the logic to check the communication status value before raising the exception.
#162
> Bugfix: Correct handling of communication status in InMemoryRpcClient

- src/main/java/org/eclipse/uprotocol/client/usubscription/v3/InMemoryUSubscriptionClient.java
- src/test/java/org/eclipse/uprotocol/client/usubscription/v3/InMemoryUSubscriptionClientTest.java
> Update unsubscription request to include subscriber details

- src/main/java/org/eclipse/uprotocol/communication/UPayload.java
- src/test/java/org/eclipse/uprotocol/communication/UPayloadTest.java
Adding a method to unpack the payload from a UMessage
#169
> Add UPayload::unpack() of UMessage

- src/main/java/org/eclipse/uprotocol/transport/builder/UMessageBuilder.java
- src/test/java/org/eclipse/uprotocol/communication/InMemoryRpcClientTest.java
- src/test/java/org/eclipse/uprotocol/transport/builder/UMessageBuilderTest.java
- src/test/java/org/eclipse/uprotocol/transport/validator/UAttributeValidatorTest.java
We need to validate parameters passed to the constructors of the static builder methods.
#168
> Validate parameters passed to UMessageBuilder

- pom.xml
up-java pre-dates open sourcing uProtocol. Initial releases to maven central took on the up-spec version numbering which led to confusion as the patch number of up-java wasn't a direct correlation with the specifications. The decision was made (to fast) to then switch to 0.x.x for up-java however this further confused folks who go to maven central and see that v0.x is newer than v1.x.
To clean this up, we will switch up-java to version 2.x.x and moving forward, we will follow SEMVER requirements for major, minor, and patch updates.
#166
> Fix version in maven central and follow SEMVER requirements

- pom.xml
No changes to the interfaces, only updating the tag to reference the latest version of up-spec
> Update up-spec tag to v1.6.0-alpha.3

- src/main/java/org/eclipse/uprotocol/client/usubscription/v3/InMemoryUSubscriptionClient.java
- src/main/java/org/eclipse/uprotocol/client/usubscription/v3/USubscriptionClient.java
- src/test/java/org/eclipse/uprotocol/client/usubscription/v3/InMemoryUSubscriptionClientTest.java
The passed handler is not used or needed so removing this attribute.
#177
> Remove SubscriptionChangeHandler from unregisterForNotifications

- pom.xml
- src/main/java/org/eclipse/uprotocol/uuid/factory/UuidUtils.java
- src/main/java/org/eclipse/uprotocol/uuid/validate/UuidValidator.java
- src/test/java/org/eclipse/uprotocol/uuid/factory/UUIDFactoryTest.java
- src/test/java/org/eclipse/uprotocol/uuid/factory/UuidUtilsTest.java
- src/test/java/org/eclipse/uprotocol/uuid/serializer/UuidSerializerTest.java
- src/test/java/org/eclipse/uprotocol/uuid/validator/UuidValidatorTest.java
Also improved encapsulation of UuidUtils class and reduced code duplication.
> Fix UUID variant validation

- pom.xml
- src/main/java/org/eclipse/uprotocol/transport/builder/UMessageBuilder.java
- src/main/java/org/eclipse/uprotocol/transport/validator/UAttributesValidator.java
- src/main/java/org/eclipse/uprotocol/uuid/factory/UuidUtils.java
- src/test/java/org/eclipse/uprotocol/communication/InMemoryRpcClientTest.java
- src/test/java/org/eclipse/uprotocol/transport/builder/UMessageBuilderTest.java
- src/test/java/org/eclipse/uprotocol/transport/validator/UAttributesValidatorTest.java
- src/test/java/org/eclipse/uprotocol/uuid/factory/UuidUtilsTest.java
- src/test/resources/logback-test.xml
Some of the UAttributes properties are defined as unsigned integers in
the protocol specification. However, Java does not have native support for
unsigned types, which can lead to issues when dealing with values that exceed
the maximum value of a signed integer.
Java 8 has introduced support for handling unsigned integers through methods
in the Integer and Long classes. This commit updates the codebase to utilize
these methods where appropriate, ensuring that unsigned integer values are
handled correctly.
> Fix usage of unsigned integers
